
name: Modified Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        java-version:
        - '8'
        - '11'
        - '17'
        - '21'
        distribution:
        - temurin
        - corretto
        profile:
        - test-direct
        - test-no-direct
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test (${{ matrix.os }}, ${{ matrix.java-version }}, ${{ matrix.distribution }}, ${{ matrix.profile }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/clojure/clojure', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v4
    - run: touch optcd-3.txt
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distribution }}
        cache: maven
    - run: touch optcd-4.txt
    - name: Build with Maven
      run: mvn -ntp -B -P${{ matrix.profile }} clean test
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test (${{ matrix.os }}, ${{ matrix.java-version }}, ${{
          matrix.distribution }}, ${{ matrix.profile }})
        path: /home/runner/inotifywait-log-test (${{ matrix.os }}, ${{ matrix.java-version
          }}, ${{ matrix.distribution }}, ${{ matrix.profile }}).csv
    name: test (${{ matrix.os }}, ${{ matrix.java-version }}, ${{ matrix.distribution
      }}, ${{ matrix.profile }})
'on':
- push
- workflow_dispatch
